name: release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: install libreoffice
        run: |
          sudo apt update
          sudo apt install libreoffice
      - name: checkout
        uses: actions/checkout@v2
      - run: yarn ci
      - name: bundle
        run: |
          PATH=./node_modules/.bin:$PATH
          yarn gen
          parcel build \
            --public-url https://soenkehahn.github.io/pathfinder/ \
            --no-source-maps \
            src/index.html
      - name: deploy to github-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
